<?php

namespace ContainerDRtnYkL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GHsdD9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G_hsdD9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G_hsdD9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController::create' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::create()', 'getTaskControllercreateService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
            'App\\Controller\\TaskController::toggle' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::toggle()', 'getTaskControllertoggleService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::index()', 'getTaskControllerindexService', true],
            'App\\Controller\\TaskController:create' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::create()', 'getTaskControllercreateService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::delete()', 'getTaskControllerdeleteService', true],
            'App\\Controller\\TaskController:toggle' => ['privates', '.service_locator.p847NwN.App\\Controller\\TaskController::toggle()', 'getTaskControllertoggleService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::create' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::toggle' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:create' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:toggle' => '?',
        ]);
    }
}
