<?php

namespace ContainerDRtnYkL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p847NwN.App\Controller\TaskController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p847NwN.App\\Controller\\TaskController::index()'] = ($container->privates['.service_locator.p847NwN'] ?? $container->load('get_ServiceLocator_P847NwNService'))->withContext('App\\Controller\\TaskController::index()', $container);
    }
}
