<?php

namespace ContainerAbt8Xcj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p847NwN.App\Controller\TaskController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p847NwN.App\\Controller\\TaskController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskService' => ['privates', 'App\\Service\\TaskService', 'getTaskServiceService', true],
        ], [
            'taskService' => 'App\\Service\\TaskService',
        ]))->withContext('App\\Controller\\TaskController::create()', $container);
    }
}
