<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDRtnYkL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDRtnYkL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDRtnYkL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDRtnYkL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDRtnYkL\App_KernelDevDebugContainer([
    'container.build_hash' => 'DRtnYkL',
    'container.build_id' => 'a327d6fe',
    'container.build_time' => 1733959872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDRtnYkL');
